version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - helpdesk_postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=helpdesk_history_db
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - helpdesk_mongo_data:/data/db

  helpdesk-config:
    image: helpdesk-config
    ports:
      - "8888:8888"

  helpdesk-server:
    image: helpdesk-server
    ports:
      - "8082:8082"
    depends_on:
      - helpdesk-config

  helpdesk-tickets-service:
    image: helpdesk-tickets-service
    ports:
      - "8083:8083"
    depends_on:
      - helpdesk-config

  helpdesk-history-service:
    image: helpdesk-history-service
    ports:
      - "8084:8084"
    depends_on:
      - helpdesk-config

  helpdesk-email-service:
    image: helpdesk-email-service
    ports:
      - "8085:8085"
    depends_on:
      - helpdesk-config

  helpdesk-gateway:
    image: helpdesk-gateway
    ports:
      - "8080:8080"
    depends_on:
      - helpdesk-config

volumes:
  helpdesk_postgres_data:
  helpdesk_mongo_data: